---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Nginx Server on Debian Family
  apt:
    name=nginx
    state=latest

- name: Replace nginx
  template:
     src=templates/nginx.conf
     dest=/etc/nginx/nginx.conf

- name: Add virtual domain in NGINX
  vars:
    fastcgi_pass_path: /var/run/php/php7.4-fpm.sock
  template:
    src=templates/nginx_vhosts.conf
    dest=/etc/nginx/sites-available/{{ virtual_domain }}
  #notify: nginx restart

- name: Enables new site
  file:
   src: "/etc/nginx/sites-available/{{ virtual_domain }}"
   dest: "/etc/nginx/sites-enabled/{{ virtual_domain }}"
   state: link
   #notify: Reload Nginx

- name: —Åreate directory
  file:
    path=/var/www/html/{{ virtual_domain }}
    mode=0755
    owner=www-data
    group=www-data
    state=directory

- name: site phpinfo
  template:
    src: "templates/phpinfo.php"
    dest: "/var/www/html/{{ virtual_domain }}/phpinfo.php"
    owner: www-data
    group: www-data
    mode: '0755'
#    recurse: yes
  #notify: nginx restart

- name: site index
  template:
    src: "templates/index.html"
    dest: "/var/www/html/{{ virtual_domain }}/index.html"
    owner: www-data
    group: www-data
    mode: '0755'


#   - name: Removes "default" site
#     file:
#       path: "/etc/nginx/sites-enabled/default"
#       state: absent
#     notify: Reload Nginx
