---
# tasks file for mysql
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install MariaDB Server on Debian Family
  apt:
    name=mariadb-server
    state=latest